### PR TITLE
cherry-pick visualizer fixes

### PR DESCRIPTION
**Pull request by mkuron**
for #2585

### CODE REVIEW

**Comment by RudolfWeeber** [comment]
@jngrad, will you merge this, or should I?
-- 
Dr. Rudolf Weeber
Institute for Computational Physics
Universität Stuttgart
Allmandring 3
70569 Stuttgart
Germany
Phone: +49(0)711/685-67717
Email: weeber@icp.uni-stuttgart.de
http://www.icp.uni-stuttgart.de/~icp/Rudolf_Weeber

**Comment by jngrad** [comment]
I'm confused here. I was already preparing the tarball and did not expect any new change to the 4.0.2rc branch. The plan was for me to backport espressomd#2751 and then let @mkuron know he can test the PR on MacOS, not the other way around. espressomd#2677 is not a bug. Also, there is this change now:
```diff
-                t = p.bl.e[k]
+                t = p.bl[k]
```
It comes from espressomd#2629, which is not part of the milestone. Why did cherry-picking introduce it? Is it a dependency of 2677?

**Comment by mkuron** [comment]
I had some time earlier, so I just tested it straight away. The `.e` removal does not matter. `e` is the array data member, but the class also provides an `operator[]` for direct element access.

So please just cherry-pick b5c125a17b099eafd0981aa33c4e26d9312a8035, ignore my other pull request, and make the release. I do not need to test it again.

**Comment by RudolfWeeber** [comment]
On Thu, Apr 25, 2019 at 06:51:47AM -0700, Jean-Noël Grad wrote:
> I'm confused here. I was already preparing the tarball and did not expect any new change to the 4.0.2rc branch. The plan was for me to backport espressomd#2751 and then let @mkuron know he can test the PR on MacOS, not the other way around. espressomd#2677 is not a bug. Also, there is this change now:
> ```diff
> -                t = p.bl.e[k]
> +                t = p.bl[k]
> ```
> It comes from espressomd#2629, which is not part of the milestone. Why did cherry-picking introduce it? Is it a dependency of 2677?
That's how I understood it, too. You can make a decision about #2677, depending on how much work you would have to redo.
#2629 should definitely not leak in.

**Comment by jngrad** [comment]
I did not plan on including #2677 because of the work involved in checking for dependencies in previous PRs. Also, it is not a critical bug and is mostly relevant for the 4.1 milestone, where dihedral functions are refactored. espressomd#2751 is already merged in 4.0.2rc.

**Pull request closed without merging**
